// Copyright 2009-2014 Information & Computational Sciences, JHI. All rights
// reserved. Use is subject to the accompanying licence terms.

package curlywhirly.gui;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

import curlywhirly.data.*;

import scri.commons.gui.*;

public class ControlsPanelNB extends JPanel implements ActionListener, ChangeListener
{
	private final WinMain winMain;
	private DataSet dataSet;

    /** Creates new form ControlsPanelNB */
    public ControlsPanelNB(WinMain winMain)
	{
        initComponents();

		this.winMain = winMain;

		axisPanel.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
		RB.setText(lblAxesTitle, "gui.ControlPanel.axesTitle");
		RB.setText(lblX, "gui.ControlPanel.lblX");
		RB.setText(lblY, "gui.ControlPanel.lblY");
		RB.setText(lblZ, "gui.ControlPanel.lblZ");

		axisLabelPanel.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
		RB.setText(lblAxisLabelOptions, "gui.ControlPanel.axisLabelOptions");
		RB.setText(chkAxisLabels, "gui.ControlPanel.axisLabels");
		RB.setText(chkDatasetLabels, "gui.ControlPanel.datasetLabels");

		chkAxisLabels.setSelected(Prefs.guiChkAxisLabels);
		chkDatasetLabels.setSelected(Prefs.guiChkDatasetLabels);
		chkAxisLabels.addActionListener(this);
		chkDatasetLabels.addActionListener(this);

        spherePanel.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
		pointSizeSlider.setMinimum(1);
		pointSizeSlider.setMaximum(100);
		pointSizeSlider.setValue(50);
		pointSizeSlider.addChangeListener(this);

		toggleEnabled(false);
    }

	private void addComboModels()
	{
		String[] axisLabels = dataSet.getAxisLabels();
		// set the data headers as the model for the combo boxes that allow selection of variables
		xCombo.setModel(new DefaultComboBoxModel<String>(axisLabels));
		yCombo.setModel(new DefaultComboBoxModel<String>(axisLabels));
		zCombo.setModel(new DefaultComboBoxModel<String>(axisLabels));

		xCombo.addActionListener(this);
		yCombo.addActionListener(this);
		zCombo.addActionListener(this);

		resetComboBoxes();
	}

	public void resetComboBoxes()
	{
		// set the combos to display the currently selected index of the variables they display
		xCombo.setSelectedIndex(0);
		yCombo.setSelectedIndex(1);
		zCombo.setSelectedIndex(2);
	}

	@Override
	public void actionPerformed(ActionEvent e)
	{
		if (e.getSource() == xCombo)
		{
			int index = xCombo.getSelectedIndex();
			dataSet.setCurrX(index);
			winMain.getDataPanel().updateTableModel();
		}

		else if (e.getSource() == yCombo)
		{
			int index = yCombo.getSelectedIndex();
			dataSet.setCurrY(index);
			winMain.getDataPanel().updateTableModel();
		}

		else if (e.getSource() == zCombo)
		{
			int index = zCombo.getSelectedIndex();
			dataSet.setCurrZ(index);
			winMain.getDataPanel().updateTableModel();
		}

		else if (e.getSource() == chkAxisLabels)
		{
			Prefs.guiChkAxisLabels = !Prefs.guiChkAxisLabels;
			chkDatasetLabels.setEnabled(Prefs.guiChkAxisLabels);
		}

		else if (e.getSource() == chkDatasetLabels)
			Prefs.guiChkDatasetLabels = !Prefs.guiChkDatasetLabels;
	}

	public void toggleEnabled(boolean enabled)
	{
		lblX.setEnabled(enabled);
		lblY.setEnabled(enabled);
		lblZ.setEnabled(enabled);
		axisPanel.setEnabled(enabled);
		lblAxesTitle.setEnabled(enabled);
		xCombo.setEnabled(enabled);
		yCombo.setEnabled(enabled);
		zCombo.setEnabled(enabled);
		lblAxisLabelOptions.setEnabled(enabled);
		axisPanel.setEnabled(enabled);
		chkAxisLabels.setEnabled(enabled);
		chkDatasetLabels.setEnabled(enabled);
        pointSizeSlider.setEnabled(enabled);
        spherePanelLabel.setEnabled(enabled);
        spherePanel.setEnabled(enabled);
        sizeSliderLabel.setEnabled(enabled);

		if (enabled)
			chkDatasetLabels.setEnabled(Prefs.guiChkAxisLabels);
	}

	public void setDataSet(DataSet dataSet)
	{
		this.dataSet = dataSet;

		if (dataSet == null)
		{
			// Blank out the combo boxes if we don't have a dataset
			xCombo.setModel(new DefaultComboBoxModel<String>());
			yCombo.setModel(new DefaultComboBoxModel<String>());
			zCombo.setModel(new DefaultComboBoxModel<String>());
		}
		else
			addComboModels();

		toggleEnabled(dataSet != null);
	}

	@Override
	public void stateChanged(ChangeEvent e)
	{
		if (e.getSource() == pointSizeSlider)
		{
			float sliderVal = pointSizeSlider.getValue();
			float min = pointSizeSlider.getMinimum();
			float max = pointSizeSlider.getMaximum();
			float blah = ((sliderVal-min)/(max-1f) * (2f-0.2f) + 0.2f);
			winMain.getOpenGLPanel().setPointSize(blah);
		}
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAxesTitle = new javax.swing.JLabel();
        axisPanel = new javax.swing.JPanel();
        lblX = new javax.swing.JLabel();
        xCombo = new javax.swing.JComboBox<String>();
        lblZ = new javax.swing.JLabel();
        yCombo = new javax.swing.JComboBox<String>();
        lblY = new javax.swing.JLabel();
        zCombo = new javax.swing.JComboBox<String>();
        axisLabelPanel = new javax.swing.JPanel();
        chkAxisLabels = new javax.swing.JCheckBox();
        chkDatasetLabels = new javax.swing.JCheckBox();
        lblAxisLabelOptions = new javax.swing.JLabel();
        spherePanelLabel = new javax.swing.JLabel();
        spherePanel = new javax.swing.JPanel();
        pointSizeSlider = new javax.swing.JSlider();
        sizeSliderLabel = new javax.swing.JLabel();

        lblAxesTitle.setText("Data to display:");

        axisPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        lblX.setText("x-axis:");

        xCombo.setBorder(null);

        lblZ.setText("z-axis:");

        yCombo.setBorder(null);

        lblY.setText("y-axis:");

        zCombo.setBorder(null);

        javax.swing.GroupLayout axisPanelLayout = new javax.swing.GroupLayout(axisPanel);
        axisPanel.setLayout(axisPanelLayout);
        axisPanelLayout.setHorizontalGroup(
            axisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(axisPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(axisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblX)
                    .addComponent(lblY)
                    .addComponent(lblZ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(axisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        axisPanelLayout.setVerticalGroup(
            axisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(axisPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(axisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblX)
                    .addComponent(xCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(axisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblY)
                    .addComponent(yCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(axisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblZ)
                    .addComponent(zCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        axisLabelPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        chkAxisLabels.setText("Show axis labels");

        chkDatasetLabels.setText("Use dataset labels");

        javax.swing.GroupLayout axisLabelPanelLayout = new javax.swing.GroupLayout(axisLabelPanel);
        axisLabelPanel.setLayout(axisLabelPanelLayout);
        axisLabelPanelLayout.setHorizontalGroup(
            axisLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(axisLabelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(axisLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkAxisLabels)
                    .addComponent(chkDatasetLabels))
                .addContainerGap())
        );
        axisLabelPanelLayout.setVerticalGroup(
            axisLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(axisLabelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkAxisLabels)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkDatasetLabels)
                .addContainerGap())
        );

        lblAxisLabelOptions.setText("Axis label options:");

        spherePanelLabel.setText("Sphere options:");

        spherePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        sizeSliderLabel.setText("Size:");

        javax.swing.GroupLayout spherePanelLayout = new javax.swing.GroupLayout(spherePanel);
        spherePanel.setLayout(spherePanelLayout);
        spherePanelLayout.setHorizontalGroup(
            spherePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spherePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sizeSliderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pointSizeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        spherePanelLayout.setVerticalGroup(
            spherePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spherePanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(spherePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pointSizeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sizeSliderLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(axisPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(axisLabelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAxesTitle)
                            .addComponent(lblAxisLabelOptions)
                            .addComponent(spherePanelLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(spherePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAxesTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(axisPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAxisLabelOptions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(axisLabelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spherePanelLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spherePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel axisLabelPanel;
    private javax.swing.JPanel axisPanel;
    private javax.swing.JCheckBox chkAxisLabels;
    private javax.swing.JCheckBox chkDatasetLabels;
    private javax.swing.JLabel lblAxesTitle;
    private javax.swing.JLabel lblAxisLabelOptions;
    private javax.swing.JLabel lblX;
    private javax.swing.JLabel lblY;
    private javax.swing.JLabel lblZ;
    javax.swing.JSlider pointSizeSlider;
    private javax.swing.JLabel sizeSliderLabel;
    private javax.swing.JPanel spherePanel;
    private javax.swing.JLabel spherePanelLabel;
    private javax.swing.JComboBox<String> xCombo;
    private javax.swing.JComboBox<String> yCombo;
    private javax.swing.JComboBox<String> zCombo;
    // End of variables declaration//GEN-END:variables

}