// Copyright 2009-2022 Information & Computational Sciences, JHI. All rights
// reserved. Use is subject to the accompanying licence terms.

package jhi.curlywhirly.gui.dialog;

import scri.commons.gui.*;

import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;
import java.util.*;

public class DuplicateDataPointsPanelNB extends JPanel
{
	/**
	 * Creates new form NBDuplicateMarkersPanel
	 */
	public DuplicateDataPointsPanelNB(ArrayList<String> duplicates)
	{
		initComponents();

		setBackground(Color.WHITE);

		// Column headers
		String[] columnNames = {RB.getString("gui.dialog.NBDuplicateDataPointsDialog.column1")};

		// Fill the data array with the string values from the list
		Object[][] data = new Object[duplicates.size()][1];

		for (int i = 0; i < duplicates.size(); i++)
			data[i][0] = duplicates.get(i);

		table.setModel(new DefaultTableModel(data, columnNames)
		{
			@Override
			public boolean isCellEditable(int rowIndex, int mColIndex)
			{
				return false;
			}
		});

		RB.setText(label1, "gui.dialog.NBDuplicateDataPointsDialog.label1");
		RB.setText(label2, "gui.dialog.NBDuplicateDataPointsDialog.label2");
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{

		label1 = new javax.swing.JLabel();
		label2 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		table = new javax.swing.JTable();

		label1.setText("The imported data contains one or more duplicated data points.");

		label2.setText("Only the first instance of each data point has been imported into CurlyWhirly.");

		table.setModel(new javax.swing.table.DefaultTableModel(new Object[][]{

		}, new String[]{

		}));
		table.setEnabled(false);
		jScrollPane2.setViewportView(table);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(label1).addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
					.addContainerGap())
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(label1)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(label2)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
					.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
	}// </editor-fold>//GEN-END:initComponents


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JLabel label1;
	private javax.swing.JLabel label2;
	private javax.swing.JTable table;
	// End of variables declaration//GEN-END:variables

}