// Copyright 2009-2014 Information & Computational Sciences, JHI. All rights
// reserved. Use is subject to the accompanying licence terms.

package curlywhirly.gui.dialog;

import curlywhirly.gui.CWUtils;
import java.awt.*;
import java.awt.event.*;
import java.lang.management.*;
import java.text.*;
import javax.swing.*;

import scri.commons.gui.*;

class AboutPanelNB extends JPanel implements ActionListener
{
	public AboutPanelNB()
	{
		initComponents();

		initWebStuff();
		setBackground(Color.white);
		p2.setBackground(Color.white);
		iconPanel.setBackground(Color.white);

		webLabel.addActionListener(this);

		String javaVer = System.getProperty("java.version");
		long freeMem = (ManagementFactory.getMemoryMXBean().getHeapMemoryUsage().getMax()
				- ManagementFactory.getMemoryMXBean().getHeapMemoryUsage().getUsed());
		NumberFormat nf = NumberFormat.getInstance();

		copyrightLabel.setText(RB.format("gui.AboutPanelNB.copyrightLabel", "\u0026"));
		RB.setText(nameLabel, "gui.AboutPanelNB.nameLabel");
		versionLabel.setText("CurlyWhirly - " + Install4j.VERSION);
		javaLabel.setText(RB.format("gui.AboutPanelNB.javaLabel", javaVer));
		memLabel.setText(RB.format("gui.AboutPanelNB.memLabel", nf.format((long)(freeMem/1024f/1024f)) + " MB"));
		localeLabel.setText(RB.format("gui.AboutPanelNB.localeLabel", java.util.Locale.getDefault()));

		jhiIcon.setText("");
		jhiIcon.setIcon(Icons.getIcon("ABOUT"));
		cimmytIcon.setText("");
		cimmytIcon.setIcon(Icons.getIcon("ABOUT-MASAGRO"));
	}

	private void initWebStuff()
	{
		jhiIcon.setCursor(new Cursor(Cursor.HAND_CURSOR));
		jhiIcon.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent event)
			{
				CWUtils.visitURL("http://www.hutton.ac.uk");
			}
		});

		cimmytIcon.setCursor(new Cursor(Cursor.HAND_CURSOR));
		cimmytIcon.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent event)
			{
				CWUtils.visitURL("http://masagro.cimmyt.org");
			}
		});
	}

	public void actionPerformed(ActionEvent e)
	{
		final String curlyHTML = "http://bioinf.hutton.ac.uk/curlywhirly";

		if(e.getSource() == webLabel)
			CWUtils.visitURL(curlyHTML);
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        p2 = new javax.swing.JPanel();
        localeLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        copyrightLabel = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        javaLabel = new javax.swing.JLabel();
        memLabel = new javax.swing.JLabel();
        webLabel = new scri.commons.gui.matisse.HyperLinkLabel();
        iconPanel = new javax.swing.JPanel();
        jhiIcon = new javax.swing.JLabel();
        cimmytIcon = new javax.swing.JLabel();

        localeLabel.setForeground(java.awt.Color.gray);
        localeLabel.setText("Current Locale:");

        nameLabel.setText("Gordon Stephen, Iain Milne, Micha Bayer,Paul Shaw and David Marshall");

        copyrightLabel.setText("Copyright (C) 2009-2014, Information & Computational Sciences, JHI");

        versionLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        versionLabel.setText("CurlyWhirly - x.xx.xx.xx");

        javaLabel.setForeground(java.awt.Color.gray);
        javaLabel.setText("Java version:");

        memLabel.setForeground(java.awt.Color.gray);
        memLabel.setText("Memory available to JVM:");

        webLabel.setText("http://bioinf.hutton.ac.uk/curlywhirly");

        iconPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        jhiIcon.setText("JHI");
        iconPanel.add(jhiIcon);

        cimmytIcon.setText("CIMMYT");
        iconPanel.add(cimmytIcon);

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(versionLabel)
                            .addComponent(copyrightLabel)
                            .addComponent(nameLabel)
                            .addComponent(javaLabel)
                            .addComponent(memLabel)
                            .addComponent(localeLabel)
                            .addComponent(webLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addComponent(iconPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(versionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(webLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(copyrightLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLabel)
                .addGap(18, 18, 18)
                .addComponent(javaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(memLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(localeLabel)
                .addGap(38, 38, 38)
                .addComponent(iconPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cimmytIcon;
    private javax.swing.JLabel copyrightLabel;
    private javax.swing.JPanel iconPanel;
    private javax.swing.JLabel javaLabel;
    private javax.swing.JLabel jhiIcon;
    private javax.swing.JLabel localeLabel;
    private javax.swing.JLabel memLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel p2;
    private javax.swing.JLabel versionLabel;
    scri.commons.gui.matisse.HyperLinkLabel webLabel;
    // End of variables declaration//GEN-END:variables


}