/*
 * AboutDialog.java
 *
 * Created on 05 February 2009, 09:59
 */

package curlywhirly.gui;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import curlywhirly.controller.*;


/**
 *
 * @author  imilne
 */
public class AboutDialog extends javax.swing.JDialog {

    /** Creates new form AboutDialog */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

		closeButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				setVisible(false);
			}
		});

		scriIcon.setText("");
		scriIcon.setIcon(new ImageIcon("res/scri.png"));

		versionLabel.setText("CurlyWhirly - " + Install4j.VERSION);

		initWebStuff();

		pack();
		setTitle("About CurlyWhirly");
		setResizable(false);
		setLocationRelativeTo(parent);
		setVisible(true);
    }

	private void initWebStuff()
	{
		final String html = "http://bioinf.scri.ac.uk/curlywhirly";
		final String scriHTML = "http://www.scri.ac.uk";

		// Turns the label into a blue mouse-over clickable link to a website
		webLabel.setForeground(Color.blue);
		webLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
		webLabel.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent event)
			{
				GUIUtils.visitURL(html);
			}
		});

		scriIcon.setCursor(new Cursor(Cursor.HAND_CURSOR));
		scriIcon.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent event)
			{
				GUIUtils.visitURL(scriHTML);
			}
		});
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        versionLabel = new javax.swing.JLabel();
        webLabel = new javax.swing.JLabel();
        copyrightLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        scriIcon = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        versionLabel.setFont(new java.awt.Font("Tahoma", 1, 18));
        versionLabel.setText("CurlyWhirly - x.xx.xx.xx");

        webLabel.setText("http://bioinf.scri.ac.uk/curlywhirly");

        copyrightLabel.setText("Copyright (C) 2009, Plant Bioinformatics Group, SCRI");

        nameLabel.setText("Micha Bayer, Iain Milne and David Marshall");

        scriIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scriIcon.setText("SCRI LOGO");

        closeButton.setText("Close");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(versionLabel)
                    .add(webLabel)
                    .add(copyrightLabel)
                    .add(nameLabel)
                    .add(scriIcon, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, closeButton))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(versionLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(webLabel)
                .add(18, 18, 18)
                .add(copyrightLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(nameLabel)
                .add(18, 18, 18)
                .add(scriIcon)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(closeButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AboutDialog dialog = new AboutDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel copyrightLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel scriIcon;
    private javax.swing.JLabel versionLabel;
    private javax.swing.JLabel webLabel;
    // End of variables declaration//GEN-END:variables

}
