package curlywhirly.gui;

import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;

import scri.commons.gui.*;

public class MovieCapturePanelNB extends JPanel
{
	private CurlyWhirly winMain;
	private MovieCaptureDialog parent;

    /** Creates new form MovieCapturePanelNB */
    public MovieCapturePanelNB(CurlyWhirly winMain, MovieCaptureDialog parent)
	{
		this.winMain = winMain;
		this.parent = parent;

        initComponents();

		setBackground(Color.WHITE);
		settingsPanel.setBackground(Color.WHITE);
		warningPanel.setBackground(Color.WHITE);

		settingsPanel.setBorder(new TitledBorder(RB.getString("gui.MovieCaptureDialog.settingsPanelTitle")));
		RB.setText(frameRateLabel, "gui.MovieCaptureDialog.frameRate");
		RB.setText(spinSpeedLabel, "gui.MovieCaptureDialog.spinSpeed");
		spinSpeedCombo.addItem(RB.getString("gui.MovieCaptureDialog.radioButtonSlow"));
		spinSpeedCombo.addItem(RB.getString("gui.MovieCaptureDialog.radioButtonMedium"));
		spinSpeedCombo.addItem(RB.getString("gui.MovieCaptureDialog.radioButtonFast"));
		spinSpeedCombo.setSelectedIndex(Prefs.guiMovieCaptureSpinSpeedIndex);
		RB.setText(warningLabel, "gui.MovieCaptureDialog.warning");

		frameRateSpinner.setModel(new SpinnerNumberModel(Prefs.guiMovieCaptureFrameRate, 1, 60, 1));

		spinSpeedCombo.addActionListener(parent);
		frameRateSpinner.addChangeListener(parent);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        settingsPanel = new javax.swing.JPanel();
        frameRateSpinner = new javax.swing.JSpinner();
        spinSpeedLabel = new javax.swing.JLabel();
        frameRateLabel = new javax.swing.JLabel();
        spinSpeedCombo = new javax.swing.JComboBox<String>();
        warningPanel = new javax.swing.JPanel();
        warningLabel = new javax.swing.JLabel();

        settingsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Capture settings:"));

        spinSpeedLabel.setLabelFor(spinSpeedCombo);
        spinSpeedLabel.setText("Spin speed:");

        frameRateLabel.setLabelFor(frameRateSpinner);
        frameRateLabel.setText("Frame rate:");

        spinSpeedCombo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                spinSpeedComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout settingsPanelLayout = new javax.swing.GroupLayout(settingsPanel);
        settingsPanel.setLayout(settingsPanelLayout);
        settingsPanelLayout.setHorizontalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frameRateLabel)
                .addGap(4, 4, 4)
                .addComponent(frameRateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(spinSpeedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinSpeedCombo, 0, 124, Short.MAX_VALUE)
                .addContainerGap())
        );
        settingsPanelLayout.setVerticalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frameRateLabel)
                    .addComponent(frameRateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinSpeedCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinSpeedLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        warningPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Estimated file size (MB): 0"));

        warningLabel.setText("<html>To reduce the size of the movie file, try reducing one or more of the following: window size, frame rate, graph spin speed. <br><br><b>Please note: during the capture process, do not resize or move the window.</b></html>");

        javax.swing.GroupLayout warningPanelLayout = new javax.swing.GroupLayout(warningPanel);
        warningPanel.setLayout(warningPanelLayout);
        warningPanelLayout.setHorizontalGroup(
            warningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warningPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(warningLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap())
        );
        warningPanelLayout.setVerticalGroup(
            warningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(warningLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(settingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(warningPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(settingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void spinSpeedComboActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_spinSpeedComboActionPerformed
    {//GEN-HEADEREND:event_spinSpeedComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spinSpeedComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JLabel frameRateLabel;
    javax.swing.JSpinner frameRateSpinner;
    javax.swing.JPanel settingsPanel;
    javax.swing.JComboBox<String> spinSpeedCombo;
    javax.swing.JLabel spinSpeedLabel;
    javax.swing.JLabel warningLabel;
    javax.swing.JPanel warningPanel;
    // End of variables declaration//GEN-END:variables

}