package curlywhirly.gui.dialog;

import java.awt.*;
import java.awt.image.*;
import java.awt.event.*;
import java.util.*;
import javax.swing.*;

import curlywhirly.gui.*;
import curlywhirly.gui.viewer.*;

import scri.commons.gui.*;

public class CustomizeColorsDialog extends JDialog implements ActionListener
{
	private boolean isOK;

	public CustomizeColorsDialog()
	{
		super(
			CurlyWhirly.winMain,
			RB.getString("gui.dialog.CustomizeColorsDialog.title"),
			true
		);

		isOK = false;

		initComponents();
		initComponents2();
		getContentPane().setBackground(Color.WHITE);

		RB.setText(label, "gui.dialog.CustomizeColorsDialog.label");

		initializeList();

		list.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent e) {
				if (e.getClickCount() == 2)
					selectColor(list);
			}
		});

		getRootPane().setDefaultButton(bClose);
		SwingUtils.addCloseHandler(this, bClose);

		pack();
		setLocationRelativeTo(CurlyWhirly.winMain);
		setResizable(false);
		setVisible(true);
	}

	private void initComponents2()
	{
		RB.setText(bClose, "gui.text.close");
		bClose.addActionListener(this);

		RB.setText(bReset, "gui.dialog.CustomizeColorsDialog.bReset");
		bReset.addActionListener(this);
	}

	public boolean isOK()
		{ return isOK; }

	@Override
	public void actionPerformed(ActionEvent e)
	{
		if (e.getSource() == bClose)
			setVisible(false);

		else if (e.getSource() == bReset)
		{
			String msg = RB.getString("gui.dialog.CustomizeColorsDialog.confirmReset");
			String[] options = new String[] {
				RB.getString("gui.dialog.CustomizeColorsDialog.reset"),
				RB.getString("gui.text.cancel")
			};

			if (TaskDialog.show(msg, TaskDialog.QST, 1, options) != 0)
				return;

			ColorPrefs.resetUserColors();
			initializeList();
		}
	}

	void initializeList()
	{
		HashMap<String, Color> colors = ColorPrefs.getColors();
		DefaultListModel<EditableColor> model = new DefaultListModel<>();

		ArrayList<String> keys = new ArrayList<>();
		for (String key: colors.keySet())
			if (key.startsWith("User."))
				keys.add(key);
		Collections.sort(keys);

		for (String key: keys)
		{
			Color c = colors.get(key);
			model.addElement(new EditableColor(c, key));
		}

		list.setModel(model);
		list.setCellRenderer(new ColorListRenderer());
	}

	private void selectColor(JList<EditableColor> list)
	{
		EditableColor ec = list.getSelectedValue();
		if (ec == null) return;

		Color newColor = JColorChooser.showDialog(this,
				RB.getString("gui.dialog.CustomizeColorsDialog.dialog"),
				ec.color);

		if (newColor == null) return;

		// Update the color in the list
		ec.color = newColor;
		// And back in the hashmap (in ColorPrefs)
		ColorPrefs.getColors().put(ec.name, ec.color);
	}

	static class ColorListRenderer extends DefaultListCellRenderer
	{
		// Set the attributes of the class and return a reference
		@Override
		public Component getListCellRendererComponent(JList list, Object o,
				int i, boolean iss, boolean chf)
		{
			super.getListCellRendererComponent(list, o, i, iss, chf);

			EditableColor ec = (EditableColor) o;

			// Set the text
			setText(ec.name.substring(5));

			// Set the icon
			BufferedImage image = new BufferedImage(20, 10, BufferedImage.TYPE_INT_RGB);
			Graphics2D g = image.createGraphics();

			Color c1 = ec.color.brighter();
			Color c2 = ec.color.darker();

			g.setPaint(new GradientPaint(0, 0, c1, 20, 10, c2));
			g.fillRect(0, 0, 20, 10);
			g.setColor(Color.black);
			g.drawRect(0, 0, 20, 10);
			g.dispose();

			setIcon(new ImageIcon(image));

			return this;
		}

		@Override
		public Insets getInsets(Insets i)
			{ return new Insets(0, 3, 0, 0); }
	}

	private static class EditableColor
	{
		public Color color;
		public String name;

		EditableColor(Color color, String name)
		{
			this.color = color;
			this.name = name;
		}

		@Override
		public String toString()
		{
			return name;
		}
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        dialogPanel1 = new scri.commons.gui.matisse.DialogPanel();
        bClose = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<EditableColor>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bClose.setText("Close");
        dialogPanel1.add(bClose);

        bReset.setText("Reset to defaults");
        dialogPanel1.add(bReset);

        label.setText("Double click an entry to change its colour:");

        jScrollPane1.setViewportView(list);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dialogPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                        .addComponent(label))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(293, Short.MAX_VALUE)
                .addComponent(dialogPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(label)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(54, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClose;
    private javax.swing.JButton bReset;
    private scri.commons.gui.matisse.DialogPanel dialogPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JList<EditableColor> list;
    // End of variables declaration//GEN-END:variables

}